### PR TITLE
Add sharing functionality

### PR DESCRIPTION
**Pull request by 4031651**

### CODE REVIEW

**Comment by doomsower** [comment]
I did a quick test, everything seems to work fine. 
But for example app iOS step 2 (Add path to React Native image library) was not necessary, since it is already covered by `RCTImage` inside example app's Podfile. So I think it should be moved into **Installation without CocoaPods** section.
I also have not time to test images atm, can you provide any example with image picker?

**Comment by 4031651** [comment]
I'll correct documentation and write an example till tomorrow evening.

**Comment by 4031651** [comment]
I updated the documentation and added an example of use.

**Pull request merged**
