### PR TITLE
Update description of `login` API method

### PR DESCRIPTION
**Pull request by a-ryazanov**
Description extended by adding Android specific behaviour.

### CODE REVIEW

**Comment by doomsower** [comment]
Don't quite understand what do you mean by
> Note that Android requires to pass an empty array as a function argument.

The docs say that login function has signature `login(scopesArray: string[]): Promise<VKLoginResult>`. This already implies that you must pass an array, and `null` or `undefined` or `string` is invalid argument. For both Android and iOS

**Comment by a-ryazanov** [comment]
This is strange, but in my case calling login method without arguments on iOS works correctly.

**Comment by doomsower** [comment]
Yeah this is possible, although not intended behavior. If you use typescript, it should warn you when you pass undefined. I think this PR adds more confusion than clarity to current docs.

**Comment by a-ryazanov** [comment]
Ok, i'm closing this.

**Pull request closed without merging**
